<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add…' => '추가',
    'Close' => '닫기',
    'Description' => '설명',
    'Drop Files Here…' => '이곳에 파일을 올리세요.',
    'Edit' => '수정',
    'Edit information' => '정보 수정',
    'Name' => '이름',
    'Remove' => '제거',
    'Save changes' => '변경사항 저장',
    'Select all' => '모두 선택',
    'Uploading images…' => '이미지를 업로드하고 있습니다.',
];
